import { base } from '../baseStyles.mjs'

export const c4Config = {
  useWidth: base.useWidth,
  useMaxWidth: base.useMaxWidth,
  boundaryFontFamily: '"Open Sans", sans-serif',
  boundaryFontSize: 14,
  boundaryFontWeight: 'normal',
  boxMargin: 10,
  c4BoundaryInRow: 2,
  c4ShapeInRow: 4,
  c4ShapeMargin: 50,
  c4ShapePadding: 20,
  component_bg_color: '#85BBF0',
  component_border_color: '#78A8D8',
  component_db_bg_color: '#85BBF0',
  component_db_border_color: '#78A8D8',
  component_dbFontFamily: '"Open Sans", sans-serif',
  component_dbFontSize: 14,
  component_dbFontWeight: 'normal',
  component_queue_bg_color: '#85BBF0',
  component_queue_border_color: '#78A8D8',
  component_queueFontFamily: '"Open Sans", sans-serif',
  component_queueFontSize: 14,
  component_queueFontWeight: 'normal',
  componentFontFamily: '"Open Sans", sans-serif',
  componentFontSize: 14,
  componentFontWeight: 'normal',
  container_bg_color: '#438DD5',
  container_border_color: '#3C7FC0',
  container_db_bg_color: '#438DD5',
  container_db_border_color: '#3C7FC0',
  container_dbFontFamily: '"Open Sans", sans-serif',
  container_dbFontSize: 14,
  container_dbFontWeight: 'normal',
  container_queue_bg_color: '#438DD5',
  container_queue_border_color: '#3C7FC0',
  container_queueFontFamily: '"Open Sans", sans-serif',
  container_queueFontSize: 14,
  container_queueFontWeight: 'normal',
  containerFontFamily: '"Open Sans", sans-serif',
  containerFontSize: 14,
  containerFontWeight: 'normal',
  diagramMarginX: 50,
  diagramMarginY: 10,
  external_component_bg_color: '#CCCCCC',
  external_component_border_color: '#BFBFBF',
  external_component_db_bg_color: '#CCCCCC',
  external_component_db_border_color: '#BFBFBF',
  external_component_dbFontFamily: '"Open Sans", sans-serif',
  external_component_dbFontSize: 14,
  external_component_dbFontWeight: 'normal',
  external_component_queue_bg_color: '#CCCCCC',
  external_component_queue_border_color: '#BFBFBF',
  external_component_queueFontFamily: '"Open Sans", sans-serif',
  external_component_queueFontSize: 14,
  external_component_queueFontWeight: 'normal',
  external_componentFontFamily: '"Open Sans", sans-serif',
  external_componentFontSize: 14,
  external_componentFontWeight: 'normal',
  external_container_bg_color: '#B3B3B3',
  external_container_border_color: '#A6A6A6',
  external_container_db_bg_color: '#B3B3B3',
  external_container_db_border_color: '#A6A6A6',
  external_container_dbFontFamily: '"Open Sans", sans-serif',
  external_container_dbFontSize: 14,
  external_container_dbFontWeight: 'normal',
  external_container_queue_bg_color: '#B3B3B3',
  external_container_queue_border_color: '#A6A6A6',
  external_container_queueFontFamily: '"Open Sans", sans-serif',
  external_container_queueFontSize: 14,
  external_container_queueFontWeight: 'normal',
  external_containerFontFamily: '"Open Sans", sans-serif',
  external_containerFontSize: 14,
  external_containerFontWeight: 'normal',
  external_person_bg_color: '#686868',
  external_person_border_color: '#8A8A8A',
  external_personFontFamily: '"Open Sans", sans-serif',
  external_personFontSize: 14,
  external_personFontWeight: 'normal',
  external_system_bg_color: '#999999',
  external_system_border_color: '#8A8A8A',
  external_system_db_bg_color: '#999999',
  external_system_db_border_color: '#8A8A8A',
  external_system_dbFontFamily: '"Open Sans", sans-serif',
  external_system_dbFontSize: 14,
  external_system_dbFontWeight: 'normal',
  external_system_queue_bg_color: '#999999',
  external_system_queue_border_color: '#8A8A8A',
  external_system_queueFontFamily: '"Open Sans", sans-serif',
  external_system_queueFontSize: 14,
  external_system_queueFontWeight: 'normal',
  external_systemFontFamily: '"Open Sans", sans-serif',
  external_systemFontSize: 14,
  external_systemFontWeight: 'normal',
  height: 60,
  messageFontFamily: '"Open Sans", sans-serif',
  messageFontSize: 12,
  messageFontWeight: 'normal',
  nextLinePaddingX: 0,
  person_bg_color: '#08427B',
  person_border_color: '#073B6F',
  personFontFamily: '"Open Sans", sans-serif',
  personFontSize: 14,
  personFontWeight: 'normal',
  system_bg_color: '#1168BD',
  system_border_color: '#3C7FC0',
  system_db_bg_color: '#1168BD',
  system_db_border_color: '#3C7FC0',
  system_dbFontFamily: '"Open Sans", sans-serif',
  system_dbFontSize: 14,
  system_dbFontWeight: 'normal',
  system_queue_bg_color: '#1168BD',
  system_queue_border_color: '#3C7FC0',
  system_queueFontFamily: '"Open Sans", sans-serif',
  system_queueFontSize: 14,
  system_queueFontWeight: 'normal',
  systemFontFamily: '"Open Sans", sans-serif',
  systemFontSize: 14,
  systemFontWeight: 'normal',
  width: 216,
  wrap: true,
  wrapPadding: 10,
}
